### PR TITLE
Fix breadcrumbs. Resolves #1383

### LINKED ISSUE #1383: 5.x: no breadcrumbs on page
Somewhere during the recent updates the newly implemented breadcrumbs on pages (Page, not `/overview`) stopped working. Could possibly be related to changes in how paths are set / treated.

### PR DESCRIPTION
**Pull request by dometto**
Also added a test

### CODE REVIEW

File: lib/gollum/views/page.rb [hunk 1]
```diff
@@ -26,14 +26,14 @@ def page_header
       end
       
       def breadcrumb
-        path = Pathname.new(@page.url_path_title)
+        path = Pathname.new(@page.url_path).parent
```
Comment (dometto) [inline lib/gollum/views/page.rb]: This is the fix proper (using `url_path` rather than `url_path_title`), the rest is some mild refactoring, taking advantage of `Pathname#parent` to make sure the page's title doesn't end up in the breadcrumb.

**Comment by dometto** [comment]
Just to make sure I've reintroduced the correct behavior, this is what it looks like now (with the page title below the crumb):

Screenshot 2019-05-17 at 13 13 44

**Comment by bartkamphorst** [comment]
> Just to make sure I've reintroduced the correct behavior, this is what it looks like now (with the page title below the crumb):

Yes, that's what's expected. Thanks for the quick PR!
